### Variables
@baseUrl = http://localhost:3000/api/users
@contentType = application/json

### base url test
GET http://localhost:3000

#############################################
# USER ENDPOINTS
#############################################

### 1. Get all users
GET {{baseUrl}}/

### 2. Register a new user (basic)
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "username": "car_enthusiast",
  "email": "john@example.com",
  "password": "SecurePass123!"
}

### 3. Login user
# @name loginRequest
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "email": "john@example.com",
  "password": "SecurePass123!"
}

### 4. Get current user profile
GET {{baseUrl}}/me
Authorization: Bearer {{loginRequest.response.body.token}}
Content-Type: {{contentType}}
